### ISSUE TITLE
onChangeCurrentValue

### ISSUE THREAD

**Issue by elliotdickison** [olahol/react-tagsinput#115]
I have a proposal (will put together a PR if it sounds reasonable): I think it would make sense to move management of the text input value to outside of the component. This could be done by adding a onChangeCurrentValue prop (for parity with the currentValue prop). This would essentially make the text input a controlled input from the end-user's perspective. This would give the user much more power over the behavior of the input value without increasing the API surface area (as clearInput could safely be removed).

**Comment by Prophet32j** [comment]
I second this. Right now I have a state conflict between components. I have state wrapping the Tags component, and I am finding multiple render calls being made because the state of the internal Tags component is keeping state of the same input field. By forcing the user to manage the state of the input instead of the Tag component, I think this would alleviate this issue.

**Comment by olahol** [comment]
There is now a prop `onChangeInput` which does this.
