### ISSUE TITLE
onChangeInput prop doesn't work

### ISSUE THREAD

**Issue by lasfin** [olahol/react-tagsinput#123]
Thanks for your library, great work.

I have a problem with onChangeInput prop, which isn't triggered.
In the example below function onChangeInput doesn't trigger at all, but onChange at inputProps works. Is it expected behaviour? Version 3.14
```
<TagsInput
    value={this.state.tags}
    onChange={this.handleChange}
    onChangeInput={() => {console.log("doesn't work")}}
    inputProps={{onChange: () => { console.log("work")  }}}
/>
```

**Comment by chin2km** [comment]
that looks like the expected behaviour

**Comment by mhlmhl** [comment]
What is the expected behavior?  It's not described...

From what I can see:

- onChangeInput is never called
- onChange is called with the index of an existing tag if the user deletes one
- onChange is called with an index > the length of the tags array if the user adds a new tag

This implies that I can ignore onChangeInput.  Is that correct?

**Comment by olahol** [comment]
`onChangeInput` is only called if the input box is controlled (https://facebook.github.io/react/docs/forms.html#controlled-components), for this to happen both `inputValue` and `onChangeInput` need to be set, if they aren't then the input box is uncontrolled.
