### ISSUE TITLE
Android Chrome does not respect delimiter keys

### ISSUE THREAD

**Issue by Mike-Sinistralis** [olahol/react-tagsinput#149]
Chrome 59.0.3071.125
Android 7.1.2; Nexus 6P Build/N2G47O

Android Chrome does not trigger any of the delimiter logic when entering the values (for example, physically hitting the comma key). This seems to be a known issue with Android and the suggested work around for it is to use keydown/keyup but I havn't had a chance to verify if this solves the problem.

**Comment by acelaya** [comment]
I'm having this issue too, but the funny thing is that the [demo page](https://olahol.github.io/react-tagsinput/) is properly working from Android.

What's the difference?

**Comment by ducdev** [comment]
It's 2019 now, and this issue is still open.

**Comment by ducdev** [comment]
It's 2019 and this issue is still postponed.

**Comment by OliverJAsh** [comment]
I found a decent explanation of the problem in [another library (which also has this issue), `react-tags`](https://github.com/i-like-robots/react-tags): https://github.com/i-like-robots/react-tags/issues/94

Extracting from there and the links within, here's how I understand the situation:

- `KeyboardEvent.key` always (?) returns `undefined` on Android. [Chrome bug, marked as won't fix](https://bugs.chromium.org/p/chromium/issues/detail?id=763559).
- We can't fallback to `KeyboardEvent.keyCode` because it's always `0`/`229` for most characters. [Chrome bug, marked as won't fix](https://bugs.chromium.org/p/chromium/issues/detail?id=118639).
- One of the default "add keys"—enter—doesn't suffer from this problem. Presumably this is because, in this case at least, `KeyboardEvent.keyCode` does return the correct value (`13`). (@acelaya This is why the demo page doesn't have this problem.)
- This other library, [`react-tags`, has a PR to fix the issue](https://github.com/i-like-robots/react-tags/pull/97), but it's been open for 2 years now.

**Comment by i-like-robots** [comment]
Hello,

I saw this issue was linking to a report of the same problem on a component I maintain which I've been trying to solve recently. This is the best "solution" I have come up with so far for supporting delimiter keys which are not mapped on soft keyboards: https://github.com/i-like-robots/react-tags/pull/181
