### ISSUE TITLE
Possible invariant violation introduced by react-tagsinput

### ISSUE THREAD

**Issue by DelvarWorld** [olahol/react-tagsinput#5]
When I install this library with `npm` and then `require` it in my project, I get this error:

    Uncaught Error: Invariant Violation: EventPluginRegistry: Cannot inject event plugin ordering more than once. You are likely trying to load more than one copy of React.

Even stranger, the error won't go away until I remove the require statement AND uninstall this from my node_modules dir with `npm uninstall react-tagsinput`

**Comment by olahol** [comment]
Can you give me a code example so that I can reproduce the issue?

As the error says this seems to be an issue with `React` loading twice, as `react-tagsinput` dependencies are up to date it might be that you have component that is running an older version of `React` or a component that has upgraded to `0.13.0-beta`. 

It also looks like it can be a result of running an out dated version of browserify
