### ISSUE TITLE
Issues using autocomplete

### ISSUE THREAD

**Issue by ulfryk** [olahol/react-tagsinput#93]
This issue appears on `example/index.html` file from this repo. When you click on `AutocompleteExample` (not in the middle but near border) the error is thrown:

```
bundle.js:25012 Uncaught TypeError: this.refs.input.focus is not a function

focus   @   bundle.js:25012
handleClick @   bundle.js:25093
ReactErrorUtils.invokeGuardedCallback   @   bundle.js:9823
executeDispatch @   bundle.js:9607
executeDispatchesInOrder    @   bundle.js:9630
executeDispatchesAndRelease @   bundle.js:9062
executeDispatchesAndReleaseTopLevel @   bundle.js:9073
forEachAccumulated  @   bundle.js:9926
processEventQueue   @   bundle.js:9239
runEventQueueInBatch    @   bundle.js:16814
handleTopLevel  @   bundle.js:16825
handleTopLevelImpl  @   bundle.js:21235
perform @   bundle.js:12188
batchedUpdates  @   bundle.js:21152
batchedUpdates  @   bundle.js:10893
dispatchEvent   @   bundle.js:21312
```

**Comment by wildeyes** [comment]
I've looked into this, it looks like the ref points to `AutosuggestContainer`, instead of an actual `input`, and so there is not focus method, for a react component (sadly!). 

I'm thinking the solution could be one or a mix of:

1. Using [`react-query`](https://www.npmjs.com/package/react-query) to find the "input" inside the ref, if the ref is not a DOM input.
2. Having a component-specific fix for `AutosuggestContainer`, perhaps by checking for the component's name. I have found that doing `AutosuggestContainer.input.focus()` works.
3. Implementing a react interface, asking that the input component must implement a focus method himself.

**Comment by wildeyes** [comment]
@olahol would love your input before pull requesting anything, when you have the time.

**Comment by olahol** [comment]
@wildeyes sorry for not getting back to you sooner, I have fixed so that at least the error does not show up now by checking if `focus` is defined on `this.refs.input` https://github.com/olahol/react-tagsinput/blob/master/src/index.js#L203-L205

**Comment by wildeyes** [comment]
@olahol would you accept a pull request implementing the first solution I proposed, "finding" the input dynamically? I would be happy to implement it (and obviously without react-query, that's just overkill)

**Comment by ncphillips** [comment]
I'm having a related issue, however instead of throwing `Uncaught TypeError: this.refs.input.focus is not a function`

 I am getting this error: `Uncaught TypeError: Cannot read property 'focus' of undefined`. 

When I set a breakpoint in the `focus` method

```
      function focus() {
        if (typeof this.refs.input.focus === 'function') {
          this.refs.input.focus();
        }

        this.handleOnFocus();
      }
```

I get this in the debugger

![image](https://cloud.githubusercontent.com/assets/824015/19040045/c9b46eb2-8958-11e6-95a0-93d5eadbfb17.png)

**Comment by olahol** [comment]
Thanks for reporting this issue again, I will check it out after work.

**Comment by ncphillips** [comment]
Hey @olahol, thanks.

After further exploration it seems this occurs with or without the autocomplete. We're using this tag with redux-form, so I'm going to try and figure out if there's a problem with how I'm initializing the TagsInput.

**Comment by ncphillips** [comment]
It looks like this is caused by me passing `handleRef` to the `inputProps` function.

We were looking to do this so we could trigger `blur` when the user presses `esc`. This isn't a major requirement, but if you know the properly way to get our hands  on the input's ref let me know!

**Comment by olahol** [comment]
Update examples using `react-autosuggest`.
